/*
 * Remote Control API
 *
 * Remote Control TV API
 *
 * API version: 1.0.0
 * Contact: alan@alanmbarr.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"database/sql"
	"encoding/json"
	"log"
	"net/http"
	"os"
	"strings"

	//not sure why
	_ "github.com/mattn/go-sqlite3"
	"github.com/nats-io/nats.go"
)

//Content object
type Content struct {
	Name string
}

//ContentList of content objects
type ContentList []Content

//WatchList returns a list of content that is triggerable
func WatchList(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	home, err := os.UserHomeDir()
	db, err := sql.Open("sqlite3", home+"/contentScript.db")
	checkErr(err)

	// query
	rows, err := db.Query("SELECT name FROM watchcontentscripts;")
	checkErr(err)

	var name string
	var contentList ContentList

	for rows.Next() {
		err = rows.Scan(&name)
		checkErr(err)
		watchContent := Content{
			Name: name,
		}
		contentList = append(contentList, watchContent)
	}

	rows.Close() //good habit to close
	b, err := json.Marshal(contentList)
	w.Write(b)

}

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}

//WatchTrigger queues up a message for the python worker to activate
func WatchTrigger(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	nc, err := nats.Connect("127.0.01:4222")
	if err != nil {
		log.Fatal(err)
	}
	defer nc.Close()

	path := strings.Split(r.URL.String(), "/")
	message := path[len(path)-1]
	//Publish the message
	if err := nc.Publish("watch", []byte(message)); err != nil {
		log.Fatal(err)
	}
}
