/*
 * Remote Control API
 *
 * Remote Control TV API
 *
 * API version: 1.0.0
 * Contact: alan@alanmbarr.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)
//Route object
type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}
//Routes array of route objects
type Routes []Route
//NewRouter creates a set of routes
func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

var routes = Routes{

	Route{
		"WatchList",
		strings.ToUpper("Get"),
		"/WatchTV/1.0.0/watch",
		WatchList,
	},

	Route{
		"WatchTrigger",
		strings.ToUpper("Post"),
		"/WatchTV/1.0.0/watch/{content}",
		WatchTrigger,
	},
}
